apiVersion: v1
kind: Service
metadata:
  labels:
    app: flagger-loadtester
  name: flagger-loadtester
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: flagger-loadtester
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
