---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-hec
type: Opaque
stringData:
  token: "83EC671B-7904-7251-A81C-71F99F50003B"
  endpoint: "https://splunk-s1-standalone-service.splunk-operator.svc.cluster.local:8088/services/collector"