---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-logs-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-logs-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-logs-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-logs-collector
subjects:
  - kind: ServiceAccount
    name: otel-logs-collector
    namespace: opentelemetry
---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-hec
type: Opaque
stringData:
  token: "83EC671B-7904-7251-A81C-71F99F50003B"
  endpoint: "https://splunk-s1-standalone-service.splunk-operator.svc.cluster.local:8088/services/collector"
  