---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-logs-collector
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-logs-collector
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-logs-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-logs-collector
subjects:
  - kind: ServiceAccount
    name: otel-logs-collector
    namespace: observability
---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-hec
  namespace: observability
type: Opaque
stringData:
  token: "00000000-0000-0000-0000-000000000000"
  endpoint: "https://splunk.example.com:8088/services/collector"