---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: minikube-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.67.5-192.168.67.10 # <--- Change this to match your minikube ip subnet
  