---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata: null
name: additional-pool
namespace: metallb-system
spec: null
addresses:
  - 10.38.240.148-10.38.240.152
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata: null
name: additional-pool
namespace: metallb-system
spec: null
ipAddressPools:
  - additional-pool