---
apiVersion: v1
kind: Service
metadata:
  name: flagger-loadtester-service
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: flagger-loadtester
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    name: flagger-loadtester